### ISSUE TITLE
I am wondering if the class `RandomWalker` is still closed? thanks

### ISSUE THREAD

**Issue by Toshihiro-Ota** [ruehlef/ribbon#1]
Hi,

First and foremost thanks a lot for releasing the code and this great work.

I am really interested in your work on “Searching for ribbons with machine learning” ([2304.09304](https://arxiv.org/abs/2304.09304)) and the concept of "ML for rigorous math". Upon reviewing the ‘ribbon_example.ipynb’ notebook within the repo, I noticed the main class `RandomWalker` is indicated as not available in the README.md file’s concluding remarks. Could you please confirm if it’s still closed, and if possible, provide access to it?

In addition, I didn’t find the reinforcement learning experiment code from the paper in the repo. Could you also provide the source code for those experiments to facilitate reproduction of the results?

Thanks in advance.

**Comment by ruehlef** [comment]
Hi,

thank you for your kind words. You can use the compiled code, but it is closed source. A colleague who is working on similar things asked us to keep it closed until they publish their results. I will make it open source as soon as their paper is published.

**Comment by Aloriosa** [comment]
Hello,
Thank you for your amazing work!
It's been a year since this issue has been opened. 
I also would love to see your RandomWalker class implementation and experimental code.
Is there a chance the source code will be released?

**Comment by ruehlef** [comment]
Hi,

I apologize for this. Unfortunately, the colleague who asked us to keep it closed code still has not published their results. I will make it available as soon as their work has appeared.
